"""empty message

Revision ID: b4fdcf2fe393
Revises: 8bd4dd15deee
Create Date: 2021-02-07 18:02:21.215856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4fdcf2fe393'
down_revision = '8bd4dd15deee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('sentiment', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('results', sa.Column('tweet', sa.String(), nullable=True))
    op.drop_column('results', 'url')
    op.drop_column('results', 'result_no_stop_words')
    op.drop_column('results', 'result_all')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('results', 'tweet')
    op.drop_column('results', 'sentiment')
    # ### end Alembic commands ###
